import 'dart:io';

/// Represents a field in a hydrated model (API model)
class HydratedField {
  final String name;
  final String type;

  /// The corresponding ID field name (if this is an object field)
  /// E.g., "user" → "userId", "attachments" → "attachmentIds"
  final String? idFieldName;

  /// Whether this field represents a hydrated object
  final bool isHydrated;

  /// Whether this field represents an ID (e.g., userId, attachmentIds)
  final bool isIdField;

  /// List type indicator if this is List<T>
  final String? listItemType;

  /// Whether to serialize the full object (toJson) instead of extracting IDs
  /// Used when DB type is dynamic (e.g., List<dynamic>) - we serialize
  /// the full hydrated object to JSON rather than extracting just the ID
  final bool serializeFullObject;

  /// The default value from @Default(...) annotation (e.g., "0", "false", "const []")
  /// Used for fields that exist only in hydrated model but not in DB model
  final String? defaultValue;

  /// Whether this field has @autoGenerated annotation (computed by backend, not settable)
  /// Fields with autoGenerated=true should NOT be included as fromDb parameters
  final bool isAutoGenerated;

  const HydratedField({
    required this.name,
    required this.type,
    this.idFieldName,
    this.isHydrated = false,
    this.isIdField = false,
    this.listItemType,
    this.serializeFullObject = false,
    this.defaultValue,
    this.isAutoGenerated = false,
  });
  
  /// Get the singular form of a plural ID field
  /// E.g., "attachmentIds" → "attachment", "userIds" → "user"
  static String singularizeIdField(String idFieldName) {
    if (idFieldName.endsWith('Ids')) {
      return idFieldName.substring(0, idFieldName.length - 3); // Remove 'Ids'
    } else if (idFieldName.endsWith('Id')) {
      return idFieldName.substring(0, idFieldName.length - 2); // Remove 'Id'
    }
    return idFieldName;
  }
}

/// Parser for analyzing hydrated models (API models) to extract field information
///
/// Extracts field declarations including annotations:
/// - @Default(...) - captures default values for fields not in DB model
/// - @autoGenerated - marks fields computed by backend (excluded from fromDb params)
///
/// The parser handles multi-line annotations and Freezed factory constructor syntax.
/// Default values are extracted to support converter generation for fields that
/// exist only in the hydrated model (not in the DB model).
class HydratedModelParser {
  /// Parse a hydrated model file to extract field information
  List<HydratedField> parseModel(String modelPath) {
    return parseFields(modelPath);
  }

  /// Parse fields from a hydrated model file
  ///
  /// Reads the Dart file and extracts field declarations from the model class.
  /// Returns a list of HydratedField objects representing each field.
  ///
  /// When [className] is given, the parser anchors to that class's factory
  /// constructor. This matters for union family files, which hold several
  /// factory constructors — the unanchored parser would take the first one.
  List<HydratedField> parseFields(String modelPath, {String? className}) {
    try {
      final file = File(modelPath);
      if (!file.existsSync()) {
        return [];
      }

      final content = file.readAsStringSync();
      return _extractFields(content, className: className);
    } catch (e) {
      // On error, return empty list - converter will use fallback heuristics
      return [];
    }
  }

  /// Extract field declarations from Dart class content
  List<HydratedField> _extractFields(String dartContent, {String? className}) {
    // For Freezed classes, look for the factory constructor pattern:
    // const factory ClassName({ ... }) = _ClassName;
    // Anchored to className when provided, falling back to the first factory
    // so oddly-named single-class files keep working.
    if (className != null) {
      final anchoredMatch = RegExp(
        'const\\s+factory\\s+${RegExp.escape(className)}\\s*\\(\\s*{([\\s\\S]*?)}\\s*\\)\\s*=',
        multiLine: true,
      ).firstMatch(dartContent);
      if (anchoredMatch != null) {
        return _parseClassBody(anchoredMatch.group(1) ?? '');
      }
    }

    var classMatch = RegExp(
      r'const\s+factory\s+\w+\s*\(\s*{([\s\S]*?)}\s*\)\s*=',
      multiLine: true,
    ).firstMatch(dartContent);

    if (classMatch != null) {
      return _parseClassBody(classMatch.group(1) ?? '');
    }

    // Fallback: try regular class definition
    classMatch = RegExp(
      r'(?:final\s+)?class\s+\w+.*?\{([\s\S]*?)\}',
      multiLine: true,
    ).firstMatch(dartContent);

    if (classMatch == null) {
      return [];
    }

    return _parseClassBody(classMatch.group(1) ?? '');
  }
  
  /// Parse the class body to extract field declarations
  ///
  /// This method extracts field information including:
  /// - Field name and type
  /// - @Default(...) annotation values for fields not in DB model
  /// - @autoGenerated annotation to exclude auto-generated fields
  List<HydratedField> _parseClassBody(String classBody) {
    final fields = <HydratedField>[];

    // First, collect all annotations that appear before field declarations
    // We need to handle multi-line annotations like:
    //   @autoGenerated
    //   @dbImmutable
    //   @Default(false)
    //   bool shadowed,

    // Normalize the content by handling multi-line annotations
    // Join lines that end with open parenthesis or have incomplete annotation
    final normalizedContent = _normalizeAnnotations(classBody);

    // Split by lines and process each potential field
    final lines = normalizedContent.split('\n');

    // Track annotations for the current field
    String? pendingDefaultValue;
    bool pendingIsAutoGenerated = false;

    int i = 0;
    while (i < lines.length) {
      var line = lines[i].trim();

      // Skip empty lines
      if (line.isEmpty) {
        i++;
        continue;
      }

      // Skip comments
      if (line.startsWith('///')) {
        i++;
        continue;
      }

      // Check for @Default annotation on this line
      // Note: This may appear inline with the field declaration (e.g., "@Default(0) int replyCount,")
      final defaultMatch = RegExp(r'@Default\s*\(\s*(.+?)\s*\)').firstMatch(line);
      if (defaultMatch != null) {
        pendingDefaultValue = defaultMatch.group(1);
        // Remove the @Default annotation from the line so field parsing works
        line = line.replaceFirst(RegExp(r'@Default\s*\(\s*.+?\s*\)'), '').trim();
        // Don't continue here - we need to process the field declaration on this same line
      }

      // Check for @autoGenerated annotation (case insensitive)
      if (RegExp(r'@autoGenerated\b', caseSensitive: false).hasMatch(line)) {
        pendingIsAutoGenerated = true;
        // Remove the annotation from the line
        line = line.replaceFirst(RegExp(r'@autoGenerated\b', caseSensitive: false), '').trim();
        // Don't continue here - process any field declaration on this line
      }

      // Check for other decorators that don't have field declarations
      // These are decorators like @JsonKey, @dbImmutable that we need to skip
      if (line.startsWith('@') && !line.contains('required')) {
        // Check if this line has a field definition after the decorators
        final fieldPattern = RegExp(
          r'(?:required\s+)?([\w<>,?\s]+?)\s+(\w+)\s*[,;=?]',
        );
        if (!fieldPattern.hasMatch(line)) {
          // No field on this line, skip it
          i++;
          continue;
        }
        // Field exists on this line, remove decorators and continue parsing
        line = line.replaceAll(RegExp(r'@\w+\s*(?:\([^)]*\))?\s*'), ' ').trim();
      }

      // Now try to extract field declaration
      // Pattern: [required] Type [?] fieldName [,;]
      // The type can include generics like List<String> or Map<String, dynamic>
      final fieldMatch = RegExp(
        r'(?:required\s+)?(\w+(?:<[^>]+>)?\??)\s+(\w+)\s*[,;=?]',
      ).firstMatch(line);

      if (fieldMatch != null) {
        final type = fieldMatch.group(1);
        final name = fieldMatch.group(2);

        if (type != null &&
            name != null &&
            !_isPrivateField(name) &&
            !_isKeyword(type) &&
            !_isKeyword(name)) {
          fields.add(HydratedField(
            name: name,
            type: type,
            defaultValue: pendingDefaultValue,
            isAutoGenerated: pendingIsAutoGenerated,
          ));
        }

        // Reset pending annotations after field is processed
        pendingDefaultValue = null;
        pendingIsAutoGenerated = false;
      }

      i++;
    }

    return fields;
  }

  /// Normalize annotations that may span multiple lines
  ///
  /// Handles cases like:
  ///   @Default(
  ///     const {}
  ///   )
  /// or
  ///   @JsonKey(name: 'reply_count')
  ///   @Default(0)
  ///
  /// Returns content with annotations normalized to single lines
  String _normalizeAnnotations(String content) {
    final lines = content.split('\n');
    final result = <String>[];
    String? buffer;
    int parenDepth = 0;

    for (final line in lines) {
      final trimmed = line.trim();

      // Check if we're in the middle of an annotation
      if (buffer != null) {
        buffer += ' $trimmed';
        // Track parenthesis depth
        for (final char in trimmed.runes) {
          final ch = String.fromCharCode(char);
          if (ch == '(') parenDepth++;
          if (ch == ')') parenDepth--;
        }

        // If we've closed all parentheses, add to result
        if (parenDepth <= 0) {
          result.add(buffer.trim());
          buffer = null;
          parenDepth = 0;
        }
        continue;
      }

      // Check if this line starts an annotation with unclosed parenthesis
      final openParens = '('.allMatches(trimmed).length;
      final closeParens = ')'.allMatches(trimmed).length;

      if (trimmed.startsWith('@') && openParens > closeParens) {
        // This annotation spans multiple lines
        buffer = trimmed;
        parenDepth = openParens - closeParens;
      } else {
        result.add(trimmed);
      }
    }

    // Handle case where annotation wasn't closed (shouldn't happen in valid Dart)
    if (buffer != null) {
      result.add(buffer.trim());
    }

    return result.join('\n');
  }
  
  /// Check if a word is a Dart keyword
  bool _isKeyword(String word) {
    const keywords = {
      'required',
      'const',
      'factory',
      'default',
      'static',
      'final',
      'var',
      'dynamic',
      'void',
    };
    return keywords.contains(word);
  }

  /// Check if a field is private (starts with underscore)
  bool _isPrivateField(String fieldName) {
    return fieldName.startsWith('_');
  }
}
