import 'dart:io';
import 'package:openapi_retrofit_generator/src/parser/model/normalized_identifier.dart';
import 'package:openapi_retrofit_generator/src/parser/openapi_parser_core.dart';
import 'package:openapi_retrofit_generator/src/utils/type_utils.dart';

import 'package:openapi_retrofit_generator/src/generator/utils/hydrated_model_parser.dart';

/// Global variable to store the models base path for enum detection
/// This is set by dartConverterTemplate when it's called
String? _modelsBasePath;

/// Global variable to store the model search directories
/// This is set by dartConverterTemplate when it's called
List<String> _modelSearchDirectories = const ['models'];

/// Info about how a standalone model maps to a union variant
///
/// e.g., Agent maps to Ai.agent() → AiAgent
class UnionVariantInfo {
  const UnionVariantInfo({
    required this.parentClassName,
    required this.factoryName,
    required this.discriminatorPropertyName,
    required this.variantClassName,
  });

  /// The parent sealed/union class name (e.g., "Ai")
  final String parentClassName;

  /// The factory method name on the parent (e.g., "agent")
  final String factoryName;

  /// The discriminator property name (e.g., "type")
  /// This field is excluded from union factory constructors by Freezed.
  final String discriminatorPropertyName;

  /// The concrete variant class converters accept/return: the Freezed clone
  /// (e.g., "AiAgent") for legacy unions, or the leaf class itself
  /// (e.g., "Agent") for sealed-ref-union families.
  final String variantClassName;
}

/// Provides template for generating model converter classes
///
/// Converters handle transformation between hydrated models and database models,
/// automatically including all fields and flagging type mismatches.
///
/// ## Default Value Fields
///
/// Fields that exist in the hydrated model (API response) but NOT in the database model
/// (e.g., computed fields like `replyCount`) are handled specially:
///
/// 1. If a field has `@Default(...)` annotation in the hydrated model and is NOT marked
///    with `@autoGenerated`, it will be included as an optional parameter in `fromDb()`
///    with its default value.
///
/// 2. Fields marked with `@autoGenerated` are EXCLUDED from `fromDb()` parameters
///    since they are computed by the backend and should not be set manually.
///
/// Example: `replyCount` has `@Default(0)` in Message class but doesn't exist in
/// DbMessage. It will appear in fromDb as: `int replyCount = 0`
///
/// This allows converters to reconstruct hydrated models with proper default values
/// for fields not persisted to the database.
String dartConverterTemplate(
  UniversalComponentClass dataClass, {
  String? hydratedModelName,
  required String hydratedModelImport,
  List<HydratedField> hydratedFields = const [],
  String? modelsBasePath,
  List<String> modelSearchDirectories = const ['models'],
  UnionVariantInfo? unionVariantInfo,
  UnionVariantInfo? dbUnionVariantInfo,
}) {
  // Store the modelsBasePath and search directories in variables that can be accessed by nested functions
  _modelsBasePath = modelsBasePath;
  _modelSearchDirectories = modelSearchDirectories;
  final dbClassName = dataClass.name.toPascal;
  final converterClassName = '${dbClassName}Converter';

  // Derive hydrated model name from Db prefix (e.g., DbMessage -> Message)
  final resolvedHydratedModelName =
      hydratedModelName ??
      (dbClassName.startsWith('Db')
          ? dbClassName.substring(2)
          : '${dbClassName}Hydrated');

  // Hydrated side union info (e.g., Agent is a variant of Ai)
  //   fromDb returns Ai (parent type) via Ai.agent() factory
  //   toDb accepts AiAgent (variant type) which has variant-specific fields
  final parentClassName = unionVariantInfo?.parentClassName;
  final unionFactoryName = unionVariantInfo?.factoryName;
  final fromDbReturnType = parentClassName ?? resolvedHydratedModelName;
  final toDbParamType =
      unionVariantInfo?.variantClassName ?? resolvedHydratedModelName;

  // DB side union info (e.g., DbAgent is a variant of Dbai)
  //   toDb returns Dbai (parent type) via Dbai.agent() factory
  //   fromDb accepts DbaiAgent (variant type) which has variant-specific fields
  final dbParentClassName = dbUnionVariantInfo?.parentClassName;
  final dbUnionFactoryName = dbUnionVariantInfo?.factoryName;
  final toDbReturnType = dbParentClassName ?? dbClassName;
  final fromDbParamType = dbUnionVariantInfo?.variantClassName ?? dbClassName;

  final fields = dataClass.parameters.toList();

  // Detect hydrated fields with dual-field support
  final detectedHydratedFields = _detectHydratedFields(fields, hydratedFields);

  // Categorize fields
  final directFields = <UniversalType>[];
  final hydratedParams = <HydratedField>[];
  final contextFields =
      <UniversalType>[]; // Fields like channelCid that come from context

  // Fields that exist ONLY in hydrated model (not in DB) with default values
  // These are fields like replyCount that have @Default(...) but no corresponding DB field
  // They should be included as optional parameters in fromDb() unless auto-generated
  final defaultValueFields = <HydratedField>[];

  // First, extract all hydrated fields from the detected fields
  hydratedParams.addAll(detectedHydratedFields.where((f) => f.isHydrated));

  // Identify fields that exist only in hydrated model with defaults (not in DB model)
  // These fields should be passed as optional parameters to fromDb()
  for (final hydratedField in hydratedFields) {
    // Skip fields that are already handled as hydrated params
    if (hydratedParams.any((h) => h.name == hydratedField.name)) {
      continue;
    }

    // Skip if this field exists in the DB model
    final existsInDb = fields.any((f) => f.name == hydratedField.name);
    if (existsInDb) {
      continue;
    }

    // Skip auto-generated fields - these are computed by backend, not settable
    if (hydratedField.isAutoGenerated) {
      continue;
    }

    // Include fields that have default values and are not auto-generated
    if (hydratedField.defaultValue != null) {
      defaultValueFields.add(hydratedField);
    }
  }

  for (final field in fields) {
    final name = field.name;
    if (name == null) continue;

    // Check if this is a hydrated object field (not in the DB)
    if (hydratedParams.any((h) => h.name == name)) {
      // Skip - already added as hydrated
      continue;
    }

    // Check if this DB field corresponds to a hydrated field
    // (e.g., userId corresponds to hydrated user, attachments corresponds to hydrated attachments)
    bool isCorrespondingToHydrated = false;
    for (final h in hydratedParams) {
      // Check if this DB field is the ID field for a hydrated parameter
      // e.g., userId is the ID for user, attachments ID field for attachments hydrated param
      if (h.idFieldName == name) {
        isCorrespondingToHydrated = true;
        break;
      }
    }
    if (isCorrespondingToHydrated) {
      // This DB field has a corresponding hydrated field
      // Check if this field also exists directly in the API model (same name)
      // If yes, it's a direct field (copy from source)
      // If no, we'll handle it in the toDb/fromDb body by extracting from the hydrated object

      final existsInApi = hydratedFields.any((f) => f.name == name);
      if (existsInApi) {
        // Field exists in both API and DB models with same name
        // Include it as a direct field
        directFields.add(field);
      }
      // If it doesn't exist in API, we skip it here and handle it via hydrated object extraction
      continue;
    }

    // Check if it's a context field
    if (_isContextField(name)) {
      contextFields.add(field);
      continue;
    }

    // Otherwise, it's a direct field
    directFields.add(field);
  }

  final transformerParams = _generateTransformerParams(
    directFields.where((f) => _isLegacyTransformField(f)).toList(),
  );
  final toDbBody = _generateToDbBody(
    dbClassName,
    resolvedHydratedModelName,
    directFields,
    contextFields,
    hydratedParams,
    discriminatorPropertyName: unionVariantInfo?.discriminatorPropertyName,
    dbParentClassName: dbParentClassName,
    dbUnionFactoryName: dbUnionFactoryName,
    dbDiscriminatorPropertyName: dbUnionVariantInfo?.discriminatorPropertyName,
  );
  final fromDbBody = _generateFromDbBody(
    dbClassName,
    resolvedHydratedModelName,
    directFields,
    hydratedParams,
    defaultValueFields,
    parentClassName: parentClassName,
    unionFactoryName: unionFactoryName,
    discriminatorPropertyName: unionVariantInfo?.discriminatorPropertyName,
    dbDiscriminatorPropertyName: dbUnionVariantInfo?.discriminatorPropertyName,
  );

  // Filter out imports - we import the whole package, so local model imports aren't needed
  // The dataClass.imports contains references to other Db* models from the configured model package.

  final toDbParams = _generateToDbParams(toDbParamType, contextFields);
  final fromDbParams = _generateFromDbParams(
    fromDbParamType,
    hydratedParams,
    defaultValueFields,
  );
  final hydratedParamsDocs = _generateHydratedParamsDocumentation(
    hydratedParams,
    defaultValueFields,
  );

  return '''
import '$hydratedModelImport' as models;

/// Auto-generated converter for $dbClassName <-> $resolvedHydratedModelName
/// 
/// This converter handles transformation between hydrated models (from backend responses)
/// and database models (for Couchbase persistence).
/// 
/// Fields are categorized as:
/// - Direct: Same type in both models, copied as-is
/// - Hydrated: Complex objects that need to be fetched/resolved (passed as parameters)
/// - Context: Provided externally (e.g., hidden, clearHistoryUsers)
class $converterClassName {
$transformerParams

  const $converterClassName(${_generateConstructorParams(directFields.where((f) => _isLegacyTransformField(f)).toList())});

  /// Convert hydrated model to database model
  /// 
  /// Direct fields (${directFields.length}): ${directFields.map((f) => f.name).join(', ')}
  /// Hydrated fields (${hydratedParams.length}): ${hydratedParams.map((f) => f.name).join(', ')}
  /// Context fields (${contextFields.length}): ${contextFields.map((f) => f.name).join(', ')}
  models.$toDbReturnType toDb($toDbParams) {
$toDbBody
  }

  /// Convert database model back to hydrated model
  /// 
  /// Reverses the toDb() transformation, reconstructing the hydrated model
  /// from its database representation.
  ///
$hydratedParamsDocs
  models.$fromDbReturnType fromDb($fromDbParams) {
$fromDbBody
  }
}

/// Singleton instance with default transformers
/// TODO: Provide actual transformer implementations
// const ${converterClassName.substring(0, 1).toLowerCase()}${converterClassName.substring(1)} = $converterClassName();
''';
}

/// Detect hydrated fields with dual-field pattern support
///
/// This function implements the intelligent dual-field detection algorithm
/// that recognizes when both ID fields (e.g., userId) and object fields (e.g., user)
/// exist and marks them appropriately.
///
/// ## Detection Logic
///
/// The algorithm categorizes fields into:
/// 1. **Hydrated fields** - Complex objects that need to be resolved (e.g., User, `List<Reaction>`)
/// 2. **ID fields** - Reference fields stored in DB (e.g., userId, `List<String>` attachmentIds)
/// 3. **Direct fields** - Same type in both models, copied as-is
///
/// ## Default Value Fields (New)
///
/// Fields with `@Default(...)` annotation that exist ONLY in the hydrated model
/// (not in DB model) and are NOT marked `@autoGenerated` are collected separately.
/// These fields are included as optional parameters in `fromDb()` to allow
/// setting their values when reconstructing hydrated models from DB.
///
/// Example: `replyCount` has `@Default(0)` in Message but no DbMessage field.
/// It will be added as: `int replyCount = 0` parameter in fromDb().
List<HydratedField> _detectHydratedFields(
  List<UniversalType> dbFields,
  List<HydratedField> hydratedFields,
) {
  final result = <HydratedField>[];
  final processedNames = <String>{};

  // First, deduplicate hydratedFields by name (keep first occurrence)
  final deduplicatedHydratedFields = <HydratedField>[];
  final seenNames = <String>{};
  for (final field in hydratedFields) {
    if (!seenNames.contains(field.name)) {
      deduplicatedHydratedFields.add(field);
      seenNames.add(field.name);
    }
  }

  // Process hydrated fields and detect relationships
  for (final hydratedField in deduplicatedHydratedFields) {
    // Check if this is an ID field (e.g., userId, attachmentIds)
    final isIdField =
        hydratedField.name.endsWith('Id') || hydratedField.name.endsWith('Ids');

    if (isIdField) {
      // This is an ID field (userId, attachmentIds, etc.)

      // Check if corresponding object field exists in hydrated model
      final singularName = HydratedField.singularizeIdField(hydratedField.name);

      // Look for both singular and plural forms of the object field
      // E.g., for "userIds", look for both "user" and "users"
      final possibleObjectFieldNames = [
        singularName, // e.g., "user" (singular)
        '${singularName}s', // e.g., "users" (plural)
      ];

      final correspondingObjectField = hydratedFields.firstWhere(
        (f) => possibleObjectFieldNames.contains(f.name),
        orElse: () => HydratedField(name: '', type: ''),
      );

      if (correspondingObjectField.name.isNotEmpty) {
        // We have both ID and object (userId + user, or userIds + users)

        // Check if the object field was already processed as hydrated
        if (processedNames.contains(correspondingObjectField.name)) {
          // Object field was already added when processing non-ID fields
          // Just add the ID field as DIRECT (maps to DB directly)
          result.add(
            HydratedField(
              name: hydratedField.name,
              type: hydratedField.type,
              idFieldName: null,
              isHydrated: false,
              isIdField: true,
            ),
          );
          processedNames.add(hydratedField.name);
        } else {
          // Process ID field as DIRECT (maps to DB directly)
          result.add(
            HydratedField(
              name: hydratedField.name,
              type: hydratedField.type,
              idFieldName: null,
              isHydrated: false,
              isIdField: true,
            ),
          );
          processedNames.add(hydratedField.name);

          // Process object field as HYDRATED (needs converter parameter)
          result.add(
            HydratedField(
              name: correspondingObjectField.name,
              type: correspondingObjectField.type,
              idFieldName: hydratedField.name, // Points back to ID field
              isHydrated: true,
              isIdField: false,
              listItemType: _extractListItemType(correspondingObjectField.type),
            ),
          );
          processedNames.add(correspondingObjectField.name);
        }
      } else {
        // ID field only, process normally
        result.add(
          HydratedField(
            name: hydratedField.name,
            type: hydratedField.type,
            isIdField: true,
          ),
        );
        processedNames.add(hydratedField.name);
      }
    } else {
      // Not an ID field

      if (processedNames.contains(hydratedField.name)) {
        // Already processed as part of ID/object pair
        continue;
      }

      // Check if there's a corresponding ID field in DB
      final possibleIdNames = [
        '${hydratedField.name}Id',
        '${hydratedField.name}Ids',
      ];

      final correspondingDbIdField = dbFields.firstWhere((f) {
        return possibleIdNames.contains(f.name);
      }, orElse: () => UniversalType(type: '', isRequired: false));

      if (correspondingDbIdField.type.isNotEmpty) {
        // This is an object field that has a corresponding ID in DB
        result.add(
          HydratedField(
            name: hydratedField.name,
            type: hydratedField.type,
            idFieldName: correspondingDbIdField.name,
            isHydrated: true,
            isIdField: false,
            listItemType: _extractListItemType(hydratedField.type),
          ),
        );
      } else {
        // Pattern 3: Check if same field name exists in DB with different type
        final dbFieldWithSameName = dbFields.firstWhere(
          (f) => f.name == hydratedField.name,
          orElse: () => UniversalType(type: '', isRequired: false),
        );

        if (dbFieldWithSameName.type.isNotEmpty) {
          // Same field name but different type - needs hydration
          final dbType = dbFieldWithSameName.toSuitableType();
          final hydratedType = hydratedField.type;

          // Check if types are different (not just nullable variations)
          if (!_typesMatch(dbFieldWithSameName, hydratedType)) {
            // Special case: if DB type is dynamic or Map<String, dynamic>,
            // we should serialize full objects instead of extracting IDs.
            // This handles cases like:
            //   - List<dynamic> options → store full serialized List<PollOption>
            //   - Map<String, dynamic> state → store serialized MessageState
            final dbBaseType = dbType
                .replaceAll('?', '')
                .replaceAll('List<', '')
                .replaceAll('>', '')
                .trim();
            // Detect when DB stores serialized data (dynamic or Map) that the
            // hydrated model represents as typed objects. Covers:
            //   dynamic, List<dynamic>, Map<String, dynamic>,
            //   Map<String, dynamic>?, List<Map<String, dynamic>>, etc.
            final isSerialized =
                dbBaseType == 'dynamic' ||
                dbType.contains('Map<String, dynamic>');
            if (isSerialized) {
              result.add(
                HydratedField(
                  name: hydratedField.name,
                  type: hydratedField.type,
                  idFieldName: hydratedField.name, // DB field name is the same
                  isHydrated:
                      true, // Still needs processing (for serialization)
                  isIdField: false,
                  serializeFullObject:
                      true, // Serialize full objects instead of extracting IDs
                  listItemType: _extractListItemType(hydratedField.type),
                ),
              );
            } else {
              // Normal type mismatch - extract IDs (existing behavior)
              result.add(
                HydratedField(
                  name: hydratedField.name,
                  type: hydratedField.type,
                  idFieldName: hydratedField.name, // DB field name is the same
                  isHydrated: true,
                  isIdField: false,
                  listItemType: _extractListItemType(hydratedField.type),
                ),
              );
            }
          } else {
            // Types match, treat as regular field
            result.add(
              HydratedField(
                name: hydratedField.name,
                type: hydratedField.type,
                isHydrated: false,
                isIdField: false,
              ),
            );
          }
        } else {
          // No corresponding field in DB, treat as regular field
          result.add(
            HydratedField(
              name: hydratedField.name,
              type: hydratedField.type,
              isHydrated: false,
              isIdField: false,
            ),
          );
        }
      }

      processedNames.add(hydratedField.name);
    }
  }

  return result;
}

/// Extract `List<T>` → T
String? _extractListItemType(String type) {
  final match = RegExp(r'List<([^>]+)>').firstMatch(type);
  return match?.group(1);
}

/// Check if database field type matches hydrated model field type
bool _typesMatch(UniversalType dbField, String hydratedType) {
  final dbType = dbField.toSuitableType();

  // Normalize types for comparison
  final normalizedDb = dbType.replaceAll('?', '').trim();
  final normalizedHydrated = hydratedType.replaceAll('?', '').trim();

  if (normalizedDb == normalizedHydrated) return true;

  // Handle common aliases/equivalents
  if (normalizedDb == 'num' &&
      (normalizedHydrated == 'double' || normalizedHydrated == 'int')) {
    return true;
  }
  if (normalizedDb == 'dynamic' || normalizedHydrated == 'dynamic') return true;

  return false;
}

/// Check if a field is a context field (not from the source model)
bool _isContextField(String fieldName) {
  const contextFieldNames = {'channelCid', 'channel_cid'};
  return contextFieldNames.contains(fieldName);
}

/// Check if a field is a legacy transform field (for backwards compatibility)
bool _isLegacyTransformField(UniversalType field) {
  // This is for handling transformer functions for fields that truly need transformation
  // In most cases with the new hydration detection, this won't be needed
  return false;
}

String _generateTransformerParams(List<UniversalType> transformFields) {
  if (transformFields.isEmpty) return '';

  final buffer = StringBuffer();
  for (final field in transformFields) {
    final fieldName = field.name;
    var dbType = field.toSuitableType();
    // Prefix Db* types with models since they're from the configured model package.
    dbType = _prefixDbTypes(dbType);
    buffer.writeln('  /// Transformer for $fieldName field');
    buffer.writeln('  final $dbType Function(dynamic) ${fieldName}ToDb;');
    buffer.writeln();
  }
  return buffer.toString();
}

/// Prefix Db* types with models. namespace
String _prefixDbTypes(String type) {
  // Pattern to match Db* types that aren't already prefixed
  final dbTypePattern = RegExp(r'\bDb([A-Z][a-zA-Z0-9]*)');
  return type.replaceAllMapped(
    dbTypePattern,
    (match) => 'models.${match.group(0)}',
  );
}

String _generateConstructorParams(List<UniversalType> transformFields) {
  if (transformFields.isEmpty) return '';

  final params = transformFields
      .map((f) => 'required this.${f.name}ToDb')
      .join(',\n    ');
  return '{\n    $params,\n  }';
}

String _generateToDbParams(
  String hydratedModelName,
  List<UniversalType> contextFields,
) {
  if (contextFields.isEmpty) return 'models.$hydratedModelName source';

  final params = contextFields
      .map((f) {
        final type = f.toSuitableType();
        final required = f.isRequired ? 'required ' : '';
        return '$required$type ${f.name},';
      })
      .join('\n    ');

  return '''
    models.$hydratedModelName source, {
    $params
  }''';
}

/// Generate parameters for fromDb() method signature with hydrated parameters
///
/// Includes:
/// - Hydrated object parameters (complex objects that need to be fetched)
/// - Default value parameters (fields with @Default(...) not in DB model, not auto-generated)
String _generateFromDbParams(
  String dbClassName,
  List<HydratedField> hydratedParams,
  List<HydratedField> defaultValueFields,
) {
  final hasParams = hydratedParams.isNotEmpty || defaultValueFields.isNotEmpty;
  if (!hasParams) {
    return 'models.$dbClassName source';
  }

  final buffer = StringBuffer();
  buffer.write('models.$dbClassName source, {\n');

  // Hydrated object parameters (complex objects that need to be resolved)
  // Skip serializeFullObject fields — they are deserialized inline from the DB
  // document via .fromJson() and don't need an external lookup parameter.
  for (final field in hydratedParams) {
    if (field.serializeFullObject) continue;
    final baseType = field.listItemType ?? field.type;
    final type = field.listItemType != null
        ? 'List<models.$baseType>'
        : 'models.$baseType';
    final defaultValue = field.listItemType != null ? ' = const []' : '';
    // Add 'required' for non-nullable parameters without defaults
    final isNullable = field.type.endsWith('?') || field.listItemType != null;
    final required = (!isNullable && defaultValue.isEmpty) ? 'required ' : '';
    // The parser now includes ? in the type if the field is nullable
    // So we don't need to add it in the template
    buffer.write('    $required$type ${field.name}$defaultValue,\n');
  }

  // Default value parameters - fields not in DB model but with default values
  // These are fields like replyCount that are computed/derived, not stored
  for (final field in defaultValueFields) {
    final dartDefaultValue = _convertDefaultToDart(field.defaultValue!);
    // For types with generics, extract the base type(s) and prefix with models.
    // E.g., "List<User>" -> "List<models.User>"
    final prefixedType = _prefixModelTypes(field.type);
    buffer.write('    $prefixedType ${field.name} = $dartDefaultValue,\n');
  }

  buffer.write('  }');
  return buffer.toString();
}

/// Convert a default value string from @Default annotation to valid Dart code
///
/// Handles cases like:
/// - "0" -> "0"
/// - "false" -> "false"
/// - "const []" -> "const []"
/// - "const {}" -> "const {}"
/// - "\"text\"" -> "\"text\""
String _convertDefaultToDart(String defaultValue) {
  // Already a valid Dart expression
  if (defaultValue.startsWith('const ')) {
    return defaultValue;
  }

  // Handle string literals (they should already have quotes)
  if ((defaultValue.startsWith('"') && defaultValue.endsWith('"')) ||
      (defaultValue.startsWith("'") && defaultValue.endsWith("'"))) {
    return defaultValue;
  }

  // Handle numeric, boolean, and null values - return as-is
  return defaultValue;
}

/// Generate documentation for hydrated parameters
///
/// Includes documentation for both hydrated object parameters and
/// default value parameters (fields not in DB model but with default values)
String _generateHydratedParamsDocumentation(
  List<HydratedField> hydratedParams,
  List<HydratedField> defaultValueFields,
) {
  final hasParams = hydratedParams.isNotEmpty || defaultValueFields.isNotEmpty;
  if (!hasParams) {
    return '';
  }

  final buffer = StringBuffer();
  buffer.writeln('  /// Hydrated parameters:');

  for (final field in hydratedParams) {
    if (field.serializeFullObject) {
      buffer.writeln(
        '  /// - ${field.name}: ${field.type} (deserialized inline from DB via .fromJson())',
      );
    } else if (field.idFieldName != null) {
      buffer.writeln(
        '  /// - [${field.name}]: ${field.type} object for ${field.idFieldName} field',
      );
    } else {
      buffer.writeln('  /// - [${field.name}]: ${field.type} object');
    }
  }

  // Document default value parameters (not stored in DB, computed/derived)
  for (final field in defaultValueFields) {
    buffer.writeln(
      '  /// - [${field.name}]: ${field.type} with default ${field.defaultValue} (not stored in DB)',
    );
  }

  return buffer.toString();
}

/// Check if a type is an enum by reading its definition from the models
bool _isEnumType(String type) {
  // Remove nullable marker
  final cleanType = type.replaceAll('?', '').trim();

  // If it's a List or contains brackets, it's not an enum
  if (cleanType.contains('<') || cleanType.contains('[')) {
    return false;
  }

  // If no base path is configured, we can't check, so assume it's not an enum
  if (_modelsBasePath == null || _modelsBasePath!.isEmpty) {
    return false;
  }

  try {
    // Try to find the enum definition in the models directory
    // Check in the configured search directories
    final snakeCaseName = _camelToSnakeCase(cleanType);

    for (final dir in _modelSearchDirectories) {
      final path = '$_modelsBasePath/$dir/$snakeCaseName.dart';
      final file = File(path);

      if (file.existsSync()) {
        final content = file.readAsStringSync();
        // Check if this file defines an enum
        if (content.contains('enum $cleanType') ||
            content.contains('enum $cleanType ')) {
          return true;
        }
      }
    }
  } catch (e) {
    // If we can't read the file or any error occurs, fall back to false
  }

  return false;
}

/// Prefix model type names with models. namespace
///
/// Handles both simple types (User -> models.User) and generic types (`List<User>` -> `List<models.User>`)
/// Excludes built-in types like int, bool, String, double, dynamic, etc.
String _prefixModelTypes(String type) {
  // List of built-in Dart types that should NOT be prefixed
  const builtInTypes = {
    'int',
    'double',
    'bool',
    'String',
    'dynamic',
    'void',
    'Null',
    'Object',
    'List',
    'Map',
    'Set',
    'Iterable',
    'Future',
    'Stream',
  };

  // Helper to check if a type name is a built-in type
  bool isBuiltIn(String typeName) {
    return builtInTypes.contains(typeName);
  }

  // Replace user-defined type names inside generic type parameters
  return type.replaceAllMapped(RegExp(r'\b([A-Z][a-zA-Z0-9]*)\b'), (match) {
    final typeName = match.group(1)!;
    // Don't prefix already prefixed types (models.Something)
    if (match.start > 0 && type[match.start - 1] == '.') {
      return typeName;
    }
    // Don't prefix built-in types
    if (isBuiltIn(typeName)) {
      return typeName;
    }
    // Prefix user-defined types
    return 'models.$typeName';
  });
}

/// Convert camelCase to snake_case
String _camelToSnakeCase(String str) {
  return str
      .replaceAllMapped(
        RegExp(r'[A-Z]'),
        (match) => '_${match.group(0)!.toLowerCase()}',
      )
      .replaceFirst('_', '');
}

String _generateToDbBody(
  String dbClassName,
  String hydratedModelName,
  List<UniversalType> directFields,
  List<UniversalType> contextFields,
  List<HydratedField> hydratedParams, {
  String? discriminatorPropertyName,
  String? dbParentClassName,
  String? dbUnionFactoryName,
  String? dbDiscriminatorPropertyName,
}) {
  final buffer = StringBuffer();

  // For DB union variants, use the parent class factory (e.g., models.Dbai.agent())
  // Otherwise, use the standalone class constructor (e.g., models.DbAgent())
  final constructorCall =
      (dbParentClassName != null && dbUnionFactoryName != null)
      ? 'models.$dbParentClassName.$dbUnionFactoryName'
      : 'models.$dbClassName';

  buffer.writeln('    return $constructorCall(');

  // Context fields first
  for (final field in contextFields) {
    buffer.writeln('      ${field.name}: ${field.name},');
  }

  // Direct fields - copy as-is with null handling for defaults
  // Skip discriminator fields for union variants (set automatically by Freezed)
  for (final field in directFields) {
    final name = field.name;
    if (name == discriminatorPropertyName &&
        discriminatorPropertyName != null) {
      continue;
    }
    if (name == dbDiscriminatorPropertyName &&
        dbDiscriminatorPropertyName != null) {
      continue;
    }
    final hasDefault = field.defaultValue != null;
    final isNullable = field.nullable || !field.isRequired;

    if (hasDefault && isNullable) {
      buffer.writeln('      $name: source.$name,');
    } else {
      buffer.writeln('      $name: source.$name,');
    }
  }

  // Hydrated fields in reverse - try to extract IDs from objects
  // For fields like flaggedBy: User -> flaggedBy: String, access .id property
  // Also for ID-only fields like sharedLocationId that don't exist in API model
  for (final hydratedField in hydratedParams) {
    // Check if this field should be serialized as full objects (not ID extraction)
    // This happens when the DB type is dynamic (e.g., List<dynamic> options)
    if (hydratedField.serializeFullObject) {
      final fieldName = hydratedField.name;
      final isNullable = hydratedField.type.endsWith('?');
      final nullOp = isNullable ? '?.' : '.';

      if (hydratedField.listItemType != null) {
        // For lists, serialize each object to JSON: List<PollOption> -> List<dynamic>
        buffer.writeln(
          '      $fieldName: source.$fieldName$nullOp map((e) => e.toJson()).toList(),',
        );
      } else {
        // For single objects, serialize to JSON
        buffer.writeln('      $fieldName: source.$fieldName$nullOp toJson(),');
      }
      continue;
    }

    // Check if this hydrated field corresponds to a DB field with the same name
    // If so, try to extract the ID from the object
    if (hydratedField.idFieldName == hydratedField.name) {
      // This is a Pattern 2 field (same name, different type)
      // Try to extract ID from the object
      final fieldName = hydratedField.name;

      // Determine nullability from the field type
      final isNullable = hydratedField.type.endsWith('?');
      final nullOp = isNullable ? '?.' : '.';

      // Check if this is an enum field
      if (_isEnumType(hydratedField.type)) {
        // For enums, use .toJson() to get the string representation
        buffer.writeln('      $fieldName: source.$fieldName$nullOp toJson(),');
      } else if (hydratedField.listItemType != null) {
        // For lists, map over to extract IDs: List<User> -> List<String>
        buffer.writeln(
          '      $fieldName: source.$fieldName$nullOp map((e) => e.id).toList(),',
        );
      } else {
        // For single objects: User -> String
        buffer.writeln('      $fieldName: source.$fieldName$nullOp id,');
      }
    } else if (hydratedField.idFieldName != null &&
        hydratedField.idFieldName!.isNotEmpty) {
      // This hydrated field has a corresponding ID field in the DB
      // Only extract if the ID field doesn't already exist as a direct field
      // (i.e., it doesn't exist in the API model)
      final idFieldName = hydratedField.idFieldName!;
      final idFieldAlreadyDirect = directFields.any(
        (f) => f.name == idFieldName,
      );

      if (!idFieldAlreadyDirect) {
        // The ID field only exists in DB, not in API model
        // Extract the ID from the hydrated object
        final sourceFieldName = hydratedField.name;
        final sourceFieldNullable = hydratedField.type.endsWith('?');
        final nullOp = sourceFieldNullable ? '?.' : '.';

        buffer.writeln(
          '      $idFieldName: source.$sourceFieldName$nullOp id,',
        );
      }
    }
  }

  buffer.writeln('    );');
  return buffer.toString();
}

/// Generate the fromDb() method body that converts DB model back to hydrated model
///
/// Includes direct fields from DB model, hydrated object parameters, and
/// default value fields (fields not in DB model but with default values)
/// Exposes the internal hydrated-field detection for use by the union converter builder.
///
/// Returns only the fields that are "hydrated" (i.e., need to be passed as
/// constructor parameters in `fromDb()`).
List<HydratedField> detectVariantHydratedParams(
  List<UniversalType> dbFields,
  List<HydratedField> hydratedModelFields,
) {
  return _detectHydratedFields(
    dbFields,
    hydratedModelFields,
  ).where((f) => f.isHydrated).toList();
}

/// Holds resolved information for one variant inside a union dispatcher converter.
class UnionVariantConverterInfo {
  const UnionVariantConverterInfo({
    required this.factoryName,
    required this.staticFieldName,
    required this.converterClassName,
    required this.dbVariantFreezedClass,
    required this.hydratedVariantFreezedClass,
    required this.fromDbParams,
  });

  /// Discriminator factory name, e.g. `'audio'` or `'urlPreview'`
  final String factoryName;

  /// Name of the static const field on the dispatcher, e.g. `'_audio'`
  final String staticFieldName;

  /// Name of the variant's individual converter class, e.g. `'DbAudioFileConverter'`
  final String converterClassName;

  /// Freezed-generated concrete class for the DB side, e.g. `'DbFileAudio'`
  final String dbVariantFreezedClass;

  /// Freezed-generated concrete class for the hydrated side, e.g. `'FileAudio'`
  final String hydratedVariantFreezedClass;

  /// Extra named parameters that the variant converter's `fromDb()` requires
  final List<HydratedField> fromDbParams;
}

/// Generate a union dispatcher converter class.
///
/// Produces a class with:
/// - `static const` instances of each variant's individual converter
/// - `toDb()` with an exhaustive switch on hydrated Freezed variant types
/// - `fromDb()` with an exhaustive switch on DB Freezed variant types
///
/// Using exhaustive switch expressions means the Dart compiler emits a
/// compile error whenever a new union variant is added to the sealed class
/// but not handled here, preventing silent runtime failures.
String dartUnionConverterTemplate({
  required String dbUnionClassName,
  required String hydratedUnionClassName,
  required List<UnionVariantConverterInfo> variants,
  required String hydratedModelImport,
  String? hydratedUnknownClass,
  String? dbUnknownClass,
}) {
  final converterClassName = '${dbUnionClassName}Converter';

  // Aggregate all unique fromDb params across all variants so the dispatcher
  // can expose a single named-parameter list.
  final aggregatedParams = <String, HydratedField>{};
  for (final v in variants) {
    for (final p in v.fromDbParams) {
      aggregatedParams.putIfAbsent(p.name, () => p);
    }
  }
  final unionFromDbParams = aggregatedParams.values.toList();

  // Static converter field declarations
  final staticFields = variants
      .map(
        (v) =>
            '  static const ${v.staticFieldName} = ${v.converterClassName}();',
      )
      .join('\n');

  // toDb() switch arms — all variants must be covered for exhaustiveness.
  // Sealed family unions additionally carry an Unknown fallback variant:
  // when both sides are families, unknown payloads pass through losslessly.
  final toDbArms = [
    ...variants.map(
      (v) =>
          '    models.${v.hydratedVariantFreezedClass} s => ${v.staticFieldName}.toDb(s),',
    ),
    if (hydratedUnknownClass != null)
      dbUnknownClass != null
          ? '    models.$hydratedUnknownClass s => models.$dbUnknownClass(s.json),'
          : "    models.$hydratedUnknownClass s => throw UnsupportedError('Cannot convert an unknown $hydratedUnionClassName variant to $dbUnionClassName'),",
  ].join('\n');

  // fromDb() switch arms — forward only the params that variant needs
  final fromDbArms = [
    ...variants.map((v) {
      if (v.fromDbParams.isEmpty) {
        return '    models.${v.dbVariantFreezedClass} s => ${v.staticFieldName}.fromDb(s),';
      }
      final passedArgs = v.fromDbParams
          .map((p) {
            // The union-level param is nullable; add ! when the variant requires it
            final needsAssertion = !p.type.endsWith('?');
            return '${p.name}: ${p.name}${needsAssertion ? '!' : ''}';
          })
          .join(', ');
      return '    models.${v.dbVariantFreezedClass} s => ${v.staticFieldName}.fromDb(s, $passedArgs),';
    }),
    if (dbUnknownClass != null)
      hydratedUnknownClass != null
          ? '    models.$dbUnknownClass s => models.$hydratedUnknownClass(s.json),'
          : "    models.$dbUnknownClass s => throw UnsupportedError('Cannot convert an unknown $dbUnionClassName variant to $hydratedUnionClassName'),",
  ].join('\n');

  // fromDb() method signature
  final String fromDbSignature;
  if (unionFromDbParams.isEmpty) {
    fromDbSignature = 'models.$dbUnionClassName source';
  } else {
    // All union-level params are nullable/optional; callers supply only what
    // they have since different switch arms need different params.
    final paramStr = unionFromDbParams
        .map((p) {
          final baseType = p.type.endsWith('?') ? p.type : '${p.type}?';
          return '${_prefixModelTypes(baseType)} ${p.name}';
        })
        .join(', ');
    fromDbSignature = 'models.$dbUnionClassName source, {$paramStr}';
  }

  // Relative imports for each variant's converter file so the static const
  // fields can reference the classes without a package alias prefix.
  final variantImports = variants
      .map((v) => "import '${v.converterClassName.toSnake}.dart';")
      .toSet() // deduplicate
      .join('\n');

  return '''
import '$hydratedModelImport' as models;
$variantImports

/// Auto-generated union dispatcher converter for $dbUnionClassName <-> $hydratedUnionClassName.
///
/// Dispatches to the appropriate variant converter based on the runtime type.
/// The exhaustive switch expressions guarantee a compile error when a new
/// variant is added to the sealed class without updating this dispatcher.
class $converterClassName {
  const $converterClassName();

$staticFields

  /// Convert hydrated $hydratedUnionClassName union to $dbUnionClassName union.
  models.$dbUnionClassName toDb(models.$hydratedUnionClassName source) => switch (source) {
$toDbArms
  };

  /// Convert $dbUnionClassName union back to hydrated $hydratedUnionClassName union.
  models.$hydratedUnionClassName fromDb($fromDbSignature) => switch (source) {
$fromDbArms
  };
}
''';
}

String _generateFromDbBody(
  String dbClassName,
  String hydratedModelName,
  List<UniversalType> directFields,
  List<HydratedField> hydratedParams,
  List<HydratedField> defaultValueFields, {
  String? parentClassName,
  String? unionFactoryName,
  String? discriminatorPropertyName,
  String? dbDiscriminatorPropertyName,
}) {
  final buffer = StringBuffer();

  // For union variants, use the parent class factory constructor (e.g., models.Ai.agent())
  // Otherwise, use the standalone class constructor (e.g., models.Agent())
  final constructorCall = (parentClassName != null && unionFactoryName != null)
      ? 'models.$parentClassName.$unionFactoryName'
      : 'models.$hydratedModelName';

  buffer.writeln('    return $constructorCall(');

  // Direct fields - copy as-is from DB model
  // Skip discriminator fields for union variants (set automatically by Freezed)
  for (final field in directFields) {
    final name = field.name;
    if (name == discriminatorPropertyName && parentClassName != null) continue;
    if (name == dbDiscriminatorPropertyName &&
        dbDiscriminatorPropertyName != null) {
      continue;
    }
    buffer.writeln('      $name: source.$name,');
  }

  // Hydrated fields - use parameters passed in, or deserialize inline
  for (final field in hydratedParams) {
    if (field.serializeFullObject) {
      // Self-deserializing field: DB stores Map/List<Map> and hydrated model
      // has a typed object. Reconstruct via .fromJson() directly from source.
      final baseType = (field.listItemType ?? field.type).replaceAll('?', '');
      final isNullable = field.type.endsWith('?');
      if (field.listItemType != null) {
        // List<Map<String, dynamic>> → List<TypedObject>
        final nullOp = isNullable ? '?' : '';
        buffer.writeln(
          '      ${field.name}: source.${field.name}$nullOp.map((e) => models.$baseType.fromJson(e)).toList(),',
        );
      } else if (isNullable) {
        // Map<String, dynamic>? → TypedObject?
        buffer.writeln(
          '      ${field.name}: source.${field.name} != null ? models.$baseType.fromJson(source.${field.name}!) : null,',
        );
      } else {
        // Map<String, dynamic> → TypedObject
        buffer.writeln(
          '      ${field.name}: models.$baseType.fromJson(source.${field.name}),',
        );
      }
    } else {
      buffer.writeln('      ${field.name}: ${field.name},');
    }
  }

  // Default value fields - fields not in DB model but with default values
  // These are computed/derived fields like replyCount
  for (final field in defaultValueFields) {
    buffer.writeln('      ${field.name}: ${field.name},');
  }

  buffer.writeln('    );');
  return buffer.toString();
}
