import 'package:meta/meta.dart';
import 'package:openapi_retrofit_generator/src/config/config_exception.dart';
import 'package:yaml/yaml.dart';

/// Configuration for a single custom metadata field
@immutable
class CustomMetadataField {
  /// Creates a [CustomMetadataField].
  const CustomMetadataField({
    required this.name,
    required this.annotation,
    this.annotationTemplate,
  });

  /// The name of the metadata field to look for in OpenAPI spec
  /// Can be with or without x- prefix (e.g., 'auto_generated' or 'x-auto-generated')
  final String name;

  /// The annotation to generate when this field is present and true
  /// Example: '@AutoGenerated()'
  final String annotation;

  /// Optional template for annotations that need values
  /// Use {value} as placeholder for the metadata value
  /// Example: '@CustomAnnotation({value})'
  final String? annotationTemplate;

  /// Creates a [CustomMetadataField] from [YamlMap].
  factory CustomMetadataField.fromYaml(YamlMap yaml) {
    final name = yaml['name']?.toString();
    if (name == null || name.isEmpty) {
      throw const ConfigException(
        "Custom metadata field must have a 'name' property.",
      );
    }

    final annotation = yaml['annotation']?.toString();
    if (annotation == null || annotation.isEmpty) {
      throw ConfigException(
        "Custom metadata field '$name' must have an 'annotation' property.",
      );
    }

    final annotationTemplate = yaml['annotation_template']?.toString();

    return CustomMetadataField(
      name: name,
      annotation: annotation,
      annotationTemplate: annotationTemplate,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomMetadataField &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          annotation == other.annotation &&
          annotationTemplate == other.annotationTemplate;

  @override
  int get hashCode =>
      name.hashCode ^ annotation.hashCode ^ annotationTemplate.hashCode;

  @override
  String toString() =>
      'CustomMetadataField(name: $name, annotation: $annotation, annotationTemplate: $annotationTemplate)';
}

/// Configuration for custom metadata feature
@immutable
class CustomMetadataConfig {
  /// Creates a [CustomMetadataConfig].
  const CustomMetadataConfig({
    this.enabled = false,
    this.fields = const [],
  });

  /// Whether custom metadata generation is enabled
  final bool enabled;

  /// List of custom metadata fields to process
  final List<CustomMetadataField> fields;

  /// Creates a [CustomMetadataConfig] from [YamlMap].
  factory CustomMetadataConfig.fromYaml(YamlMap? yaml) {
    if (yaml == null) {
      return const CustomMetadataConfig();
    }

    final enabled = yaml['enabled'] as bool? ?? false;

    final fieldsYaml = yaml['fields'] as YamlList?;
    List<CustomMetadataField> fields = [];

    if (fieldsYaml != null) {
      for (final fieldYaml in fieldsYaml) {
        if (fieldYaml is! YamlMap) {
          throw const ConfigException(
            "Custom metadata 'fields' must be a list of objects.",
          );
        }
        fields.add(CustomMetadataField.fromYaml(fieldYaml));
      }
    }

    return CustomMetadataConfig(
      enabled: enabled,
      fields: fields,
    );
  }

  /// Checks if custom metadata is effectively active
  bool get isActive => enabled && fields.isNotEmpty;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomMetadataConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          _listEquals(fields, other.fields);

  @override
  int get hashCode => enabled.hashCode ^ fields.hashCode;

  @override
  String toString() =>
      'CustomMetadataConfig(enabled: $enabled, fields: $fields)';

  /// Helper to compare lists
  static bool _listEquals<T>(List<T>? a, List<T>? b) {
    if (a == null) return b == null;
    if (b == null || a.length != b.length) return false;
    for (int i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
}
